# Cleaning Customer Call List

Import Necessary Tools

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as ny

Open files for cleaning

In [2]:
df = pd.read_excel('CustomerCallList.xlsx')

newdf = df.copy()




# copy()



# isna()
# dropna()
# is_duplicated()
# drop_duplicates()
# strip()
# replace()
# to_string()

In [3]:
newdf

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [4]:
# newdf.shape
# newdf.info()

cleaning Last_name using the strip method

In [5]:
newdf['Last_Name'] = newdf['Last_Name'].str.strip('/..*_')

newdf

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

Droping Not_useful_Column using drop method

In [6]:
newdf = newdf.drop(columns =['Not_Useful_Column'])
newdf

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

Rearranging Phone Number Column using

In [7]:
newdf['Phone_Number'] = newdf['Phone_Number'].apply(lambda z: str(z))


newdf['Phone_Number'] = newdf['Phone_Number'].str.replace('[^ZA-Z0-9]', '', regex = True)



newdf['Phone_Number'] = newdf['Phone_Number'].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:9])


newdf['Phone_Number'] = newdf['Phone_Number'].str.replace('--', '')


newdf['Phone_Number'] = newdf['Phone_Number'].str.replace('N', '')



newdf

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-542,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-977,93 West Main Street,No,Yes
2,1003,Walter,White,706-695-039,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-234,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-346,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-246,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-346,98 Clue Drive,N,No
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-542,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,706-695-039,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-234,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-346,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-246,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-542,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-977,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,706-695-039,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-346,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,876-678-346,"910 Tatooine Road, Tatooine",Yes,N

Splitting Address column into Three Columns

In [8]:
newdf[['Street Address', 'State', 'Zip Code']] = newdf['Address'].str.split(',', n=2, expand = True)


newdf = newdf.drop(columns = 'Address')

newdf

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street Address,State,Zip Code
0,1001,Frodo,Baggins,123-545-542,Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-977,No,Yes,93 West Main Street,None,None
2,1003,Walter,White,706-695-039,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-234,Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-346,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-246,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-346,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-542,Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,706-695-039,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-234,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-346,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-246,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-542,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-977,Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706-695-039,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876-678-346,Yes,N,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876-678-346,Yes,N,910 Tatooine Road,Tatooine,None

In [9]:
newdf['Paying Customer'] = newdf['Paying Customer'].str.replace('No', 'N')

newdf['Paying Customer'] = newdf['Paying Customer'].str.replace('N', 'No')

newdf['Paying Customer'] = newdf['Paying Customer'].str.replace('Yes', 'Y')

newdf['Paying Customer'] = newdf['Paying Customer'].str.replace('Y', 'Yes')

newdf['Paying Customer'] = newdf['Paying Customer'].str.replace('No/a', 'No')

newdf

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street Address,State,Zip Code
0,1001,Frodo,Baggins,123-545-542,Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-977,No,Yes,93 West Main Street,None,None
2,1003,Walter,White,706-695-039,No,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-234,Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-346,Yes,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-246,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-346,No,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-542,Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,706-695-039,Yes,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-234,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-346,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-246,No,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-542,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-977,Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706-695-039,Yes,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,No,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876-678-346,Yes,N,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876-678-346,Yes,N,910 Tatooine Road,Tatooine,None

In [14]:
newdf['Do_Not_Contact'] = newdf['Do_Not_Contact'].str.replace('No','N')

newdf['Do_Not_Contact'] = newdf['Do_Not_Contact'].str.replace('N','No')

newdf['Do_Not_Contact'] = newdf['Do_Not_Contact'].str.replace('Yes','Y')

newdf['Do_Not_Contact'] = newdf['Do_Not_Contact'].str.replace('Y','Yes')

# newdf['Do_Not_Contact'] = newdf['Do_Not_Contact'].str.fillna('')

newdf

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street Address,State,Zip Code
0,1001,Frodo,Baggins,123-545-542,Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-977,No,Yes,93 West Main Street,None,None
2,1003,Walter,White,706-695-039,No,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-234,Yes,Yes,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-346,Yes,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-246,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-346,No,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-542,Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,706-695-039,Yes,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-234,Yes,No,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-346,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-246,No,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-542,No,No,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-977,Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706-695-039,Yes,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,No,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876-678-346,Yes,No,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876-678-346,Yes,No,910 Tatooine Road,Tatooine,None

Droping all the NaN Value

In [25]:
for x in newdf.index:
    if newdf.loc[x, 'Do_Not_Contact'] == 'Yes':
        newdf.drop(x, inplace = True)
        
newdf

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street Address,State,Zip Code
0,1001,Frodo,Baggins,123-545-542,Yes,No,123 Shire Lane,Shire,None
2,1003,Walter,White,706-695-039,No,NaN,298 Drugs Driveway,None,None
4,1005,Jon,Snow,876-678-346,Yes,No,123 Dragons Road,None,None
6,1007,Jeff,Winger,,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-346,No,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-542,Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,706-695-039,Yes,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-234,Yes,No,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-346,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-246,No,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-542,No,No,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-977,Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706-695-039,Yes,NaN,3498 Super Lane,None,None
19,1020,Anakin,Skywalker,876-678-346,Yes,No,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876-678-346,Yes,No,910 Tatooine Road,Tatooine,None

In [26]:
 for x in newdf.index:
            if newdf.loc[x,'Phone_Number'] == '':
                newdf.drop(x, inplace = True)
                    
newdf

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street Address,State,Zip Code
0,1001,Frodo,Baggins,123-545-542,Yes,No,123 Shire Lane,Shire,None
2,1003,Walter,White,706-695-039,No,NaN,298 Drugs Driveway,None,None
4,1005,Jon,Snow,876-678-346,Yes,No,123 Dragons Road,None,None
7,1008,Sherlock,Holmes,876-678-346,No,No,98 Clue Drive,None,None
9,1010,Peter,Parker,123-545-542,Yes,No,25th Main Street,New York,None
11,1012,Harry,Potter,706-695-039,Yes,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-234,Yes,No,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-346,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-246,No,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-542,No,No,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-977,Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706-695-039,Yes,NaN,3498 Super Lane,None,None
19,1020,Anakin,Skywalker,876-678-346,Yes,No,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876-678-346,Yes,No,910 Tatooine Road,Tatooine,None

In [27]:

newdf = newdf.fillna('')
newdf

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street Address,State,Zip Code
0,1001,Frodo,Baggins,123-545-542,Yes,No,123 Shire Lane,Shire,
2,1003,Walter,White,706-695-039,No,,298 Drugs Driveway,,
4,1005,Jon,Snow,876-678-346,Yes,No,123 Dragons Road,,
7,1008,Sherlock,Holmes,876-678-346,No,No,98 Clue Drive,,
9,1010,Peter,Parker,123-545-542,Yes,No,25th Main Street,New York,
11,1012,Harry,Potter,706-695-039,Yes,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-234,Yes,No,2039 Main Street,,
13,1014,Leslie,Knope,876-678-346,Yes,No,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-246,No,No,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-542,No,No,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-977,Yes,No,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,706-695-039,Yes,,3498 Super Lane,,
19,1020,Anakin,Skywalker,876-678-346,Yes,No,910 Tatooine Road,Tatooine,
20,1020,Anakin,Skywalker,876-678-346,Yes,No,910 Tatooine Road,Tatooine,

In [29]:
for x in newdf.index:
    if newdf.loc[x,'Do_Not_Contact'] == '':
        newdf.drop(x, inplace = True)
        
newdf

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street Address,State,Zip Code
0,1001,Frodo,Baggins,123-545-542,Yes,No,123 Shire Lane,Shire,
4,1005,Jon,Snow,876-678-346,Yes,No,123 Dragons Road,,
7,1008,Sherlock,Holmes,876-678-346,No,No,98 Clue Drive,,
9,1010,Peter,Parker,123-545-542,Yes,No,25th Main Street,New York,
12,1013,Don,Draper,123-543-234,Yes,No,2039 Main Street,,
13,1014,Leslie,Knope,876-678-346,Yes,No,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-246,No,No,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-542,No,No,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-977,Yes,No,121 Paper Avenue,Pennsylvania,
19,1020,Anakin,Skywalker,876-678-346,Yes,No,910 Tatooine Road,Tatooine,
20,1020,Anakin,Skywalker,876-678-346,Yes,No,910 Tatooine Road,Tatooine,

In [31]:
newdf = newdf.to_csv('Clean_Customer_Call_List.csv', index= False)
newdf